### ISSUE TITLE
Some of Product Exercises & Most Tool Views Not Always Visible to Select

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#191] opened 2015-01-20 05:07 UTC
- [ ] In the 4 essentials product, I added the 4 separate summary exercises but the "view list does not have those same options to select" 

- [ ] In Self & team product, goal, project time, same problem with "course tools" -- the view is still showing "cool tools" which I no longer have anything called,

- [ ] same problem with all of the PDF tools

**Comment by sethrubenstein** [comment] 2015-01-21 15:25
Duplicate of existing tickets.

**Closed by sethrubenstein** 2015-01-21 15:25 UTC
Labels: duplicate

**Comment by cliffmichaelsgithub** [comment] 2015-01-21 15:27
This works now? Did you also edit the header from tools to courses in the actual course menu left side.

**Comment by sethrubenstein** [comment] 2015-01-21 15:28
Not yet thats in another ticket. Closing this bc its a duplicate of items listed in other tickets.

**Comment by cliffmichaelsgithub** [comment] 2015-01-21 15:28
Sorry if I kept creating duplicates. I'll work on avoiding that. I don't always remember that I posted certain issues. Is it possible to search a github issue by header words?

**Comment by cliffmichaelsgithub** [comment] 2015-01-21 15:35
Ok. See regular email for related question
