### ISSUE TITLE
Change Cool Tools to "Course Tools" 

### ISSUE THREAD

**Issue by cliffmichaelsgithub** [PixelRocket-Biz/cliff-michaels#179] opened 2015-01-12 23:30 UTC
Change Cool tools to Course Tools for consistency

![screen shot 2015-01-12 at 3 29 22 pm](https://cloud.githubusercontent.com/assets/6202539/5713340/dfa4c912-9a6f-11e4-80c6-de211c6db9c4.png)

**Comment by cliffmichaelsgithub** [comment] 2015-01-15 18:27
I thought you closed this issue but it still says "cool tools" where I wanted it to say "course tools".

**Comment by sethrubenstein** [comment] 2015-01-15 19:03
I closed one that you had made that was a duplicate of this one. Please check github before making an issue to ensure its not a duplicate.

**Comment by cliffmichaelsgithub** [comment] 2015-01-15 19:09
Gotcha - sorry - it's still a daunting system on me. PS - Gisselle was a bust. Next.

**Closed** 2015-01-26 08:21 UTC
